apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    ingress.kubernetes.io/client-body-buffer-size: "0"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.allow-http: "false"
  name: jenkins
spec:
  rules:
  - host: {{.DNS}}
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DNS}}
    secretName: certs
