apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: allow-internal-ingress
spec:
  podSelector:
    matchLabels:
      app: jenkins
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
    - podSelector:
        matchLabels:
          name: ingress
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Ingress  
 
